SystemOrganization addCategory: #'Metacello-Core-Constructors'!
SystemOrganization addCategory: #'Metacello-Core-Exceptions'!
SystemOrganization addCategory: #'Metacello-Core-Loaders'!
SystemOrganization addCategory: #'Metacello-Core-Members'!
SystemOrganization addCategory: #'Metacello-Core-Model'!
SystemOrganization addCategory: #'Metacello-Core-Specs'!
SystemOrganization addCategory: #'Metacello-Core-Validation'!
