pages
gettingStarted
	^HelpTopic 	
		title: 'Getting Started'
		contents: 'If you have a porject that you''d like to use Metacello with, you should start by taking the Metacello tutorial to familiar yourself with the configuration specification language. First load the tutorial code:

	ConfigurationOfMetacello project latestVersion load: #(''Tutorial'').

take the ProfStef-based toturial:

	ProfStef goOn: MetacelloConfigurationTutorialPart1.
	ProfStef goOn: MetacelloConfigurationTutorialPart2.

or take the image-based-tutorial:

	http://code.google.com/p/metacello/wiki/Tutorial

Then you should run through the Development process tutorial:

	ProfStef goOn: MetacelloDevelopmentProcess.

Other online resources:

	http://code.google.com/p/metacello/
	http://forum.world.st/Monticello-Metacello-f1460836.html
	http://groups.google.com/group/metacello
	http://code.google.com/p/metacello/wiki/APIReference
	
'