running
setUp
    "self reset"

    super setUp.
    self
        setUpRepositories;
        setUpExternalCore;
        setUpSampleCore;
        setUpBaselineOfExternalX;
        setUpBaselineOfExternalXX;
        setUpBaselineOfExternalXXX;
        setUpVersionBaselineOfExternalX;
        setUpVersionBaselineOfExternalXX;
        setUpVersionBaselineOfExternalXXX;
        setUpVersionBaselineOfExternalIV;
        setUpBaselineGithubReferenceXX;
        setUpBaselineGithubReferenceIV;
        setUpBaselineGithubReferenceV;
        setUpBaselineGithubReferenceVI;
        setUpBaselineGithubReferenceVII;
        setUpBaselineGithubReferenceVIII;
        setUpBaselineGithubReferenceIX;
        setUpBaselineGithubReferenceXI;
        setUpBaselineGithubReferenceXII;
        setUpBaselineGithubReferenceXIII;
        setUpMarianosImage;
        setUpConfigurationOfConflict;
        setUpInvalidConfigurations;
        setUpConfigurationIssue32;
        setUpBaselineIssue32;
        setUpConfigurationIssue59;
        setUpConfiguration63;
        setUpLockConfigurations;
        yourself