running
setUp
    "self reset"

    super setUp.
    self
        setUpRepositories;
        setUpExternalCore;
        setUpSampleCore;
        setUpBaselineOfExternalX;
        setUpBaselineOfExternalXX;
        setUpBaselineOfExternalXXX;
        setUpVersionBaselineOfExternalX;
        setUpVersionBaselineOfExternalXX;
        setUpVersionBaselineOfExternalXXX;
        setUpVersionBaselineOfExternalIV;
        setUpBaselineGithubReferenceXX;
        setUpBaselineGithubReferenceXXX;
        setUpBaselineGithubReferenceIV;
        setUpBaselineGithubReferenceV;
        setUpBaselineGithubReferenceVI;
        setUpBaselineGithubReferenceVII;
        setUpBaselineGithubReferenceVIII;
        setUpBaselineGithubReferenceIX;
        setUpMarianosImage;
        yourself