private
createPackage: packageName packageVersion: packageVersion in: aRepository withDefinitions: definitionArray
  | reference versionInfo |
  reference := GoferVersionReference name: packageName , packageVersion.
  aRepository
    basicStoreVersion:
      (MCVersion new
        setPackage: (MetacelloTestsMCPackage new name: reference packageName)
        info:
          (versionInfo := MCVersionInfo
            name: reference name
            id: UUID new
            message: 'This is a mock version'
            date: Date today
            time: Time now
            author: reference author
            ancestors: #())
        snapshot: (MCSnapshot fromDefinitions: definitionArray)
        dependencies: #()).
  ^ versionInfo