running
setUp
    "self reset"

    super setUp.
    self
        setUpMonticelloRepository;
        setUpConfigurationOfFoo;
        setUpConfigurationOfFeaux;
        setUpConfigurationOfProjectFie;
        setUpConfigurationOfProjectFee;
        setUpConfigurationOfFum;
        setUpConfigurationOfProjectFoe;
        setUpConfigurationOfFan;
        setUpConfigurationOfFix;
        setUpIssue77;
        setUpIssue95;
        setUpConfigurationOfSymbolic;
        setUpConfigurationOfProjectToolBox;
        setUpConfigurationOfProjectIssue115;
        setUpConfigurationOfProjectIssue136;
        setUpConfigurationOfProjectIssue125;
        yourself
