private
githubTagsJSON
  ^ '[
  {
    "name": "v3.1.3-gs",
    "zipball_url": "https://api.github.com/repos/GsDevKit/Seaside31/zipball/v3.1.3-gs",
    "tarball_url": "https://api.github.com/repos/GsDevKit/Seaside31/tarball/v3.1.3-gs",
    "commit": {
      "sha": "c7403803f1e35c77e96a10ab72f1de0c9c141fec",
      "url": "https://api.github.com/repos/GsDevKit/Seaside31/commits/c7403803f1e35c77e96a10ab72f1de0c9c141fec"
    }
  },
  {
    "name": "v3.1.3.1-gs",
    "zipball_url": "https://api.github.com/repos/GsDevKit/Seaside31/zipball/v3.1.3.1-gs",
    "tarball_url": "https://api.github.com/repos/GsDevKit/Seaside31/tarball/v3.1.3.1-gs",
    "commit": {
      "sha": "67e2224f22df1360fdfdb65199a778c5817b17e4",
      "url": "https://api.github.com/repos/GsDevKit/Seaside31/commits/67e2224f22df1360fdfdb65199a778c5817b17e4"
    }
  },
  {
    "name": "v3.1.2-gs",
    "zipball_url": "https://api.github.com/repos/GsDevKit/Seaside31/zipball/v3.1.2-gs",
    "tarball_url": "https://api.github.com/repos/GsDevKit/Seaside31/tarball/v3.1.2-gs",
    "commit": {
      "sha": "e0a75590555f9fb6d43b178c4c49475b8b56b121",
      "url": "https://api.github.com/repos/GsDevKit/Seaside31/commits/e0a75590555f9fb6d43b178c4c49475b8b56b121"
    }
  },
  {
    "name": "v3.1.2.1-gs",
    "zipball_url": "https://api.github.com/repos/GsDevKit/Seaside31/zipball/v3.1.2.1-gs",
    "tarball_url": "https://api.github.com/repos/GsDevKit/Seaside31/tarball/v3.1.2.1-gs",
    "commit": {
      "sha": "581b1889fe9a2990cde0acaa69f4ac68ed4a9156",
      "url": "https://api.github.com/repos/GsDevKit/Seaside31/commits/581b1889fe9a2990cde0acaa69f4ac68ed4a9156"
    }
  },
  {
    "name": "3.1.1-gs31",
    "zipball_url": "https://api.github.com/repos/GsDevKit/Seaside31/zipball/3.1.1-gs31",
    "tarball_url": "https://api.github.com/repos/GsDevKit/Seaside31/tarball/3.1.1-gs31",
    "commit": {
      "sha": "9c53917253e0512a8a3ffd569b6d20fea8c5179e",
      "url": "https://api.github.com/repos/GsDevKit/Seaside31/commits/9c53917253e0512a8a3ffd569b6d20fea8c5179e"
    }
  },
  {
    "name": "3.1.1.3-gs31",
    "zipball_url": "https://api.github.com/repos/GsDevKit/Seaside31/zipball/3.1.1.3-gs31",
    "tarball_url": "https://api.github.com/repos/GsDevKit/Seaside31/tarball/3.1.1.3-gs31",
    "commit": {
      "sha": "da304b220e6cb5bcb7c333a8a37bb0446f81ab74",
      "url": "https://api.github.com/repos/GsDevKit/Seaside31/commits/da304b220e6cb5bcb7c333a8a37bb0446f81ab74"
    }
  }
]
'